#ifndef MQTT_CODES_H_
#define MQTT_CODES_H_

#include <stdint.h>
namespace MQTTCore {

enum class ConnackReturnCode : uint8_t {
  MQTT_CONNACK_ACCEPTED = 0u,
  MQTT_CONNACK_REFUSED_PROTOCOL_VERSION = 1u,
  MQTT_CONNACK_REFUSED_IDENTIFIER_REJECTED = 2u,
  MQTT_CONNACK_REFUSED_SERVER_UNAVAILABLE = 3u,
  MQTT_CONNACK_REFUSED_BAD_USER_NAME_OR_PASSWORD = 4u,
  MQTT_CONNACK_REFUSED_NOT_AUTHORIZED = 5u
};

enum class SubscribeReturncode : uint8_t {
  QOS0 = 0x00,
  QOS1 = 0x01,
  QOS2 = 0x02,
  FAIL = 0X80
};

enum class DisconnectReason : uint8_t {
  USER_OK = 0,
  MQTT_UNACCEPTABLE_PROTOCOL_VERSION = 1,
  MQTT_IDENTIFIER_REJECTED = 2,
  MQTT_SERVER_UNAVAILABLE = 3,
  MQTT_MALFORMED_CREDENTIALS = 4,
  MQTT_NOT_AUTHORIZED = 5,
  TLS_BAD_FINGERPRINT = 6,
  TCP_CONNECTION_LOST = 7
};

} // namespace MQTTCore
#endif